// Fetch entity
GET http://localhost:9321/api/entity/66cd0892-2bdd-4b14-9619-8e9dabc2fa1b

###

// Fetch entity - bad uuid
GET http://localhost:9321/api/entity/db8da6-0d54-4c6f-9b94-326ebadeb404

###

// List entities
GET http://localhost:9321/api/entities

###

// Create simple entity
POST http://localhost:9321/api/entity

{
    "Name": "Example Saved In State 33",
    "TurboEncabulationRate": 2
}

### 

// Bad value for TER
POST http://localhost:9321/api/entity

{
    "ID": "db8dfea6-0d54-4c6f-9b94-326ebadeb404",
    "Name": "Example",
    "TurboEncabulationRate": null
}

### 

// Null RefractionRate
POST http://localhost:9321/api/entity

{
    "ID": "db8dfea6-0d54-4c6f-9b94-326ebadeb404",
    "Name": "Example",
    "TurboEncabulationRate": 1,
    "RefractionRate": null
}
### 

// Including value for RefractionRate
POST http://localhost:9321/api/entity

{
    "ID": "db8dfea6-0d54-4c6f-9b94-326ebadeb404",
    "Name": "Example",
    "TurboEncabulationRate": 1,
    "RefractionRate": 1
}

###

// Bad value for RefractionRate
POST http://localhost:9321/api/entity

{
    "ID": "db8dfea6-0d54-4c6f-9b94-326ebadeb404",
    "Name": "Example",
    "TurboEncabulationRate": 1,
    "RefractionRate": 1.2
}

### Delete entity

DELETE http://localhost:9321/api/entity/013dfe7c-2417-441c-a1f4-5bdd3f2ab132


### Update entity

PATCH http://localhost:9321/api/entity/013dfe7c-2417-441c-a1f4-5bdd3f2ab132

{
    "Name": "Patched name 2",
    "RefractionRate": 2
}
